# -*- coding: utf-8 -*-
"""HTTP layer: Anthropic Messages API compatibility plus three Claude Code adapters.

All three adapters exist to keep the KV prefix aligned.  A misaligned prefix
means APC collapses and every turn pays a full prefill:
  A. counter normalization: CC injects <total_tokens>N tokens left</total_tokens>
     on every request and N changes each time
  B. assistant header: the header used when generating and the header used when
     re-rendering history must be byte-identical -- obtain it from the template
     itself with a sentinel, do not hardcode newlines
  C. empty block filter: CC's assistant messages usually carry an empty text
     block, and "\n".join then emits two extra newlines
     (</think>\n\n\n\n<tool_call> instead of </think>\n\n<tool_call>).
     Two newlines are enough to zero out a thousand tokens of reuse.
A and B each have a kill switch for A/B comparisons.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch import Batcher, run_job
from eng import Eng, arc_slot_count, ddc_scratch_count, plan_sequences
from log import C, log, setup as log_setup
from qcache import turn_key
from stream import Streamer

# Stream text as it is generated instead of buffering the whole reply.
# CC_STREAM=0 restores the buffered behaviour, which is what the server did
# before: it matters if a client is confused by early text, and it is the only
# difference between the two.
STREAM = os.environ.get("CC_STREAM", "1") != "0"

E: Eng | None = None
BATCHER: "Batcher | None" = None
LK = threading.Lock()
LOGK = threading.Lock()

LOGDIR = os.environ.get("CC_LOGDIR") or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "logs")


def logit(msg: str, level: str = "info"):
    """Compatibility wrapper: the logger itself lives in log.py.

    Kept because every call site here and Eng's ``log=`` hook use this name, and
    they all pass a single argument.  The old body wrote its own timestamp and
    its own file; log.py does both, and adds the level and the tag that make a
    log line readable -- and it also owns llama.cpp's C-level output, which used
    to bypass Python entirely.
    """
    log(msg, level)


def record(obj: dict):
    """Append one structured record to logs/requests.jsonl."""
    try:
        os.makedirs(LOGDIR, exist_ok=True)
        obj = dict(obj, ts=time.strftime("%Y-%m-%dT%H:%M:%S"))
        with LOGK, open(os.path.join(LOGDIR, "requests.jsonl"), "a", encoding="utf-8") as f:
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")
    except Exception:
        pass


# A. counter normalization (CC_KEEP_CNT=1 disables it).
#
# Claude Code has a source-side fix that is strictly better than rewriting the
# text here: CLAUDE_CODE_TOTAL_TOKENS_REMINDER=infinite makes the block
# byte-stable, so the prompt no longer changes between requests at all.  See
# _cc_local.json.  This normalization stays as the fallback for clients that do
# not set it, and because it also covers the copies embedded in the environment
# block.
CNT = None if os.environ.get("CC_KEEP_CNT") else \
    re.compile(r"<total_tokens>\s*\d+\s*tokens left</total_tokens>")
CNT_FIX = "<total_tokens>" + os.environ.get("CC_CNT_N", "15000000") + " tokens left</total_tokens>"

# B/C. assistant header + empty blocks (CC_KEEP_AH=1 disables both).
AH = not os.environ.get("CC_KEEP_AH")
AH_HEAD = "<think>\n\n</think>\n\n"

# D. thinking mode (CC_THINK=1, or a request carrying an Anthropic `thinking`).
#
# The model writes its reasoning inside <think>...</think>.  By default that is
# stripped, because a client that did not ask for thinking has nowhere to put it
# and the empty-block header above is what makes a re-rendered history byte-match
# what was generated.  With thinking on it is sent as a thinking block ahead of
# the text -- and, just as importantly, rendered BACK into the history as the
# same <think>...</think> it came from.  Skipping that second half is what would
# cost the cache: the generated bytes and the re-rendered bytes would differ, and
# every request after a thinking turn would come back cold.
THINK = os.environ.get("CC_THINK", "0") == "1"     # startup default
# The live switch.  A list because it is rebound from an HTTP handler while
# request threads are reading it.  Flipping it changes the prompt (the header
# goes from the closed empty block to the open one), so the prefix changes with
# it and the next request pays one cold prefill -- inherent to changing what the
# model is asked, not something the server can avoid.
_THINK = [THINK]


def want_think(req=None) -> bool:
    """Whether this reply's reasoning goes to the client.

    Two ways in, and either is enough: the live switch (GET /think?on=1), or the
    client asking for it with an Anthropic `thinking` field -- which is how
    Claude Code asks.
    """
    return _THINK[0] or bool(req and req.get("thinking"))
# The same header, left open.  AH_HEAD closes the block, which is what tells the
# model its reasoning is already finished; this one asks it to start.
THINK_HEAD = "<think>\n"
# Thinking blocks carry a signature, and the streaming protocol sends it as a
# signature_delta just before the block closes.  cc_srv cannot produce a real
# one -- that is Anthropic's -- but it must not be omitted: clients validate the
# shape, and a block with no signature is dropped or the whole response refused.
# A stable placeholder is what other self-hosted Messages servers settled on.
THINK_SIG = "ccsrv-local-signature"

# NOTE ON LANGUAGE
# This is the one Chinese string the server puts INTO the prompt rather than in a
# comment.  It is left exactly as it was: it is part of the bytes the model sees,
# so translating it would change the token ids of every tool-bearing request and
# invalidate the captured fixtures (_d1.jsonl, _r1.jsonl, _r2.jsonl) and every
# cached baseline recorded against them.  CC_TOOLS_HINT=en selects the English
# wording for a fresh release; the default keeps recorded runs reproducible.
TOOLS_HINT_ZH = """
你可以调用工具。可用工具如下 (JSON Schema):
{tools}

调用格式 (必须严格遵守, 一次只调用一个):
<tool_call>
{{"name": "<工具名>", "arguments": {{...}}}}
</tool_call>

不需要调用工具时, 直接回复文本。
""".strip()

TOOLS_HINT_EN = """
You can call tools. The available tools are (JSON Schema):
{tools}

Call format (follow this strictly, one call at a time):
<tool_call>
{{"name": "<tool name>", "arguments": {{...}}}}
</tool_call>

When no tool is needed, reply with text directly.
""".strip()

TOOLS_HINT = TOOLS_HINT_EN if os.environ.get("CC_TOOLS_HINT") == "en" else TOOLS_HINT_ZH


def sys_txt(system) -> str:
    """CC's system field is an array of content blocks (with cache_control); pull the text out."""
    if isinstance(system, str):
        return system
    if isinstance(system, list):
        return "\n".join(b if isinstance(b, str) else b.get("text", "")
                         for b in system if isinstance(b, (str, dict)))
    return ""


def msgs_of(system, msgs: list, tools: list | None) -> list:
    """Anthropic system/messages/tools -> [(role, content)] for the template to flatten."""
    out = []
    s = sys_txt(system)
    if tools:
        sch = json.dumps([{"name": t.get("name"), "description": t.get("description", ""),
                           "parameters": t.get("input_schema", {})} for t in tools],
                         ensure_ascii=False, indent=1)
        s = (s + "\n\n" + TOOLS_HINT.format(tools=sch)).strip()
    if s:
        out.append(("system", s))
    for m in msgs:
        role = m.get("role", "user")
        c = m.get("content")
        ch = []
        think = None
        if isinstance(c, str):
            ch.append(c)
        else:
            for b in (c or []):
                bt = b.get("type")
                if bt == "text":
                    ch.append(b.get("text", ""))
                elif bt == "thinking":
                    # The reasoning this server sent out on the previous turn.
                    # It goes back as the <think> block it was generated from,
                    # so the bytes the model sees now equal the bytes it produced
                    # then -- which is what keeps the prefix reusable.
                    think = b.get("thinking", "")
                elif bt == "tool_use":
                    ch.append("<tool_call>\n" + json.dumps(
                        {"name": b.get("name"), "arguments": b.get("input", {})},
                        ensure_ascii=False) + "\n</tool_call>")
                elif bt == "tool_result":
                    inner = b.get("content")
                    if isinstance(inner, list):
                        inner = "".join(x.get("text", "") for x in inner
                                        if isinstance(x, dict))
                    ch.append("<tool_result>\n" + str(inner) + "\n</tool_result>")
        if role == "assistant" and AH:
            # C. drop the empty blocks -- do not let "\n".join invent newlines
            body = "\n".join(x for x in ch if x)
            if think is not None:
                # Rebuild the bytes the model produced, exactly.  It generated
                # "<think>\n" (from the prompt) + reasoning + "</think>\n\n" +
                # answer, so the reasoning still carries its own trailing
                # newline and nothing may be added around it -- one extra byte
                # here and every turn after a thinking turn comes back cold.
                out.append((role, f"<think>\n{think}</think>\n\n" + body))
            else:
                out.append((role, AH_HEAD + body))
        else:
            out.append((role, "\n".join(ch)))
    return out


def drop_think(t: str) -> str:
    """Strip <think>...</think> (an unclosed one too)."""
    while "<think>" in t:
        i = t.find("<think>")
        j = t.find("</think>", i)
        t = t[:i] + (t[j + 8:] if j >= 0 else "")
    return t.strip()


def split_think(t: str, opened: bool = False):
    """-> (thinking, rest).  The whole reply down to the first </think> is
    thinking; everything after it is the answer.

    ``opened`` says the PROMPT already carried the opening tag, which is what
    happens in thinking mode: prepare() ends the prompt with "<think>
", so the
    model never emits that tag itself and only the closing one appears in its
    output.  Splitting on the opening tag then finds nothing and files the whole
    reply as the answer -- which is exactly how a model that reasons perfectly
    well ends up with an empty thinking area.

    ``drop_think`` is the same split with the thinking thrown away, and the two
    have to agree on the edge cases or the buffered and streamed replies stop
    matching: an UNCLOSED <think> means the model never got to its answer, so
    all of it is thinking and ``rest`` is empty -- which is what drop_think's
    discarding-the-remainder already amounts to.

    A reply that never opens a think block has none, and ``rest`` is the whole
    thing.  The tags themselves are not part of the thinking text.
    """
    if opened:
        body = t[7:] if t.startswith("<think>") else t   # tolerate a doubled tag
        j = body.find("</think>")
        if j < 0:
            return body, ""           # never closed: all of it is reasoning
        return body[:j], drop_think(body[j + len("</think>"):])
    i = t.find("<think>")
    if i < 0:
        return "", t
    lead = t[:i]                      # text before the block is the reply's, not its reasoning
    body = t[i + len("<think>"):]
    j = body.find("</think>")
    if j < 0:
        return body, drop_think(lead)
    # The tail goes through drop_think, not just a slice.  A reply can carry
    # MORE than one block, and drop_think strips every one of them -- slicing
    # here would leave the later ones in the text, so thinking mode would send a
    # raw <think> tag the plain path removes, and the two would stop matching.
    return body[:j], drop_think(lead + body[j + len("</think>"):])


def calls_of(text: str):
    """Pull <tool_call>...</tool_call> out of generated text.  Lenient: if JSON
    parsing fails, fall back to brace matching.

    The standard library's json is awkward here -- the model often emits half a
    JSON object, so the braces are matched by hand.
    """
    pre, calls, rest = [], [], text
    while True:
        i = rest.find("<tool_call>")
        if i < 0:
            break
        j = rest.find("</tool_call>", i)
        body = rest[i + 11: j if j >= 0 else len(rest)]
        pre.append(rest[:i])
        rest = rest[j + 12:] if j >= 0 else ""
        o = None
        try:
            o = json.loads(body.strip())
        except Exception:
            k = body.find("{")
            if k >= 0:
                d = 0
                for e in range(k, len(body)):
                    d += (body[e] == "{") - (body[e] == "}")
                    if d == 0:
                        try:
                            o = json.loads(body[k:e + 1])
                        except Exception:
                            pass
                        break
        if isinstance(o, dict) and o.get("name"):
            calls.append({"name": o["name"], "arguments": o.get("arguments") or {}})
    pre.append(rest)
    return "".join(pre), calls


def sse(h, ev: str, data: dict):
    """Write one SSE frame.  False once the client is gone.

    A client that hangs up mid-stream raises ConnectionResetError on the next
    write, and there is no recovering from it -- but the generation loop keeps
    calling back for every token, so an unguarded write turns one disconnect into
    a traceback per token.  Latch it instead and go quiet -- and mark the
    connection closed, so keep-alive does not try to read the next request from
    the dead socket.
    """
    if getattr(h, "_gone", False):
        return False
    try:
        h.wfile.write(f"event: {ev}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n".encode())
        h.wfile.flush()
        return True
    except (ConnectionError, OSError):
        h._gone = True
        h.close_connection = True
        return False


def usage(i: int, o: int, cache_read: int = 0) -> dict:
    """Anthropic usage, with the cache fields filled in.

    Claude Code does not ask the server whether the cache hit -- it records
    whatever these fields say into its session transcript, and every tool that
    reports a hit rate (the statusline payload, cc-live, claude-stat) computes
    it from that transcript.  Reporting zero here means the hit rate reads as
    zero however much the local cache actually served.

    The three input fields have to add up to the prompt: ``input_tokens`` is
    what was billed as fresh input and ``cache_read_input_tokens`` is what the
    cache answered.  cc_srv has no separate write-to-cache step -- every
    forwarded token also lands in the KV -- so ``cache_creation_input_tokens``
    stays 0 and the forwarded count is reported as plain input rather than
    being counted twice.
    """
    return {"input_tokens": max(0, i - cache_read), "output_tokens": o,
            "cache_creation_input_tokens": 0, "cache_read_input_tokens": cache_read}


def prepare(req):
    """Anthropic request -> (prompt token ids, turn key).

    The turn key identifies the trailing user turn and is what the turn-keyed
    reuse layer keys on.  It is computed from the same flattened message list the
    prompt is rendered from, so the two can never disagree about what the
    question was.
    """
    m = msgs_of(req.get("system", ""), req.get("messages", []), req.get("tools") or [])
    turn = turn_key(m)
    if AH:
        # B. the assistant header cannot be hardcoded -- the layout (how many
        #    newlines, the separator before the body) belongs to the template.
        #    Render one sentinel message and take the span between the end of the
        #    base rendering and the sentinel: that is everything the template
        #    emits before an assistant body.
        #    Trap 1: do not write probe.endswith(SENT) -- the template renders a
        #            message ending in assistant completely (including
        #            <|im_end|>), so endswith never holds, tail comes back empty,
        #            and the generation prompt does not even contain
        #            '<|im_start|>assistant' (the measured divergence token was
        #            previous-turn <think> versus this-turn <|im_start|>).
        #    Trap 2: find() must start at len(base) -- that is what brings in the
        #            separator before the body, and only then are the two sides
        #            byte-identical.
        SENT = "SENTINELPROBE"
        base = E.tmpl(m, add_ass=False)
        probe = E.tmpl(m + [("assistant", SENT)], add_ass=False)
        i = probe.find(SENT, len(base))
        # D. Thinking is a TEMPLATE variable (enable_thinking) and this binding
        #    cannot pass template kwargs -- but the flag only changes this one
        #    span: off, the template closes an empty block, which is the model
        #    being told its reasoning is already done.  Leaving it OPEN is the
        #    same instruction to think, and it keeps the round trip closed: the
        #    model then produces "<think>\n" + reasoning + "</think>\n\n" + answer
        #    and msgs_of rebuilds exactly those bytes when the turn comes back.
        head = THINK_HEAD if want_think(req) else AH_HEAD
        p = base + (probe[len(base):i] if i >= 0 else "") + head
    else:
        p = E.tmpl(m, add_ass=True)
    if CNT is not None:
        # A. pin the counter to a constant -> the prefix is stable -> the fatal
        #    partial truncation is no longer needed
        p = CNT.sub(CNT_FIX, p)
    return E.tok(p), turn


def render(req) -> list[int]:
    """Compatibility shim: prompt ids only."""
    return prepare(req)[0]


class Api(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *a):
        pass

    def _head(self, code, ctype, extra=()):
        """Send a status line and headers.  False once the client is gone.

        A client that hangs up between sending its request and reading the reply
        makes the header flush raise ConnectionResetError.  There is no reply to
        make to a socket that is already dead, and letting the raise out only
        reaches do_POST's handler, which has no better move than to write the
        500 into that same dead socket.  So latch it -- with the same ``_gone``
        flag sse() uses, so the streaming path and this one agree on what
        "gone" means -- and let the caller drop the request.

        ``_hdr_sent`` records that a response has started, which is what tells
        do_POST that a failure is no longer reportable as an error reply.
        """
        if getattr(self, "_gone", False):
            return False
        try:
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            for k, v in extra:
                self.send_header(k, v)
            self.end_headers()
            self._hdr_sent = True
            return True
        except (ConnectionError, OSError):
            self._gone = True
            self.close_connection = True
            return False

    def _write(self, b):
        """Write a response body, latched the same way as _head()."""
        if getattr(self, "_gone", False):
            return False
        try:
            self.wfile.write(b)
            # Flushed here rather than left to the buffered writer: a body that
            # fits in the buffer would otherwise not touch the socket until
            # handle_one_request flushes it, so the disconnect would surface
            # outside this guard instead of setting _gone.
            self.wfile.flush()
            return True
        except (ConnectionError, OSError):
            self._gone = True
            self.close_connection = True
            return False

    def _send(self, code, obj):
        b = json.dumps(obj, ensure_ascii=False).encode()
        if not self._head(code, "application/json",
                          [("Content-Length", str(len(b)))]):
            return False
        return self._write(b)

    def do_GET(self):
        if self.path.startswith("/health"):
            return self._send(200, {"ok": True})
        if self.path.startswith("/stats"):
            return self._send(200, {"eng": E.line() if E else None})
        if self.path.startswith("/think"):
            # GET /think           -> current state
            # GET /think?on=1|0    -> set it
            if "on=" in self.path:
                v = self.path.split("on=", 1)[1].split("&")[0].strip().lower()
                _THINK[0] = v not in ("0", "false", "off", "no")
                logit(f"thinking {'on' if _THINK[0] else 'off'} (runtime switch)")
            return self._send(200, {"think": _THINK[0]})
        return self._send(404, {"error": "not found"})

    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        try:
            req = json.loads((self.rfile.read(n) if n else b"{}").decode())
        except Exception as ex:
            return self._send(400, {"type": "error", "error": {
                "type": "invalid_request_error", "message": str(ex)}})
        if self.path.startswith("/v1/messages/count_tokens"):
            return self._send(200, {"input_tokens": len(render(req)) if E else 0})
        if not self.path.startswith("/v1/messages"):
            return self._send(404, {"error": "not found"})
        try:
            self.msg(req)
        except (ConnectionError, TimeoutError) as ex:
            # The client hung up, or its socket timed out, between sending the
            # request and reading the reply -- CC reconnecting after its own
            # timeout looks exactly like this, and it is routine.  Nobody is
            # left to answer, so latch the connection closed and note it in one
            # line instead of dumping a traceback for an ordinary disconnect.
            self._gone = True
            self.close_connection = True
            logit(f"client gone before reply ({type(ex).__name__})", "warn")
        except Exception as ex:
            import traceback
            traceback.print_exc()
            # An error reply can only replace the real one if the real one has
            # not started: once the headers are out (and in streaming mode,
            # message_start with them) the client is parsing a response body,
            # and a second status line written into it is protocol corruption
            # rather than an error report.
            if not getattr(self, "_hdr_sent", False):
                self._send(500, {"type": "error", "error":
                                 {"type": "api_error", "message": str(ex)}})

    def msg(self, req):
        mdl = req.get("model", "Your_Model")
        mx = int(req.get("max_tokens") or 512)
        stream = bool(req.get("stream"))
        # Whether this reply's reasoning goes to the client.  CC_THINK turns it
        # on for everyone; a request carrying an Anthropic `thinking` field asks
        # for it directly, which is how Claude Code asks.  Defined here because
        # the streaming setup below reads it.
        think_on = want_think(req)

        stops = list(req.get("stop_sequences") or [])
        ids, turn = prepare(req)
        mid = "msg_" + uuid.uuid4().hex[:24]
        stops += ["<|im_end|>", "<|endoftext|>", "<|im_start|>"]   # template control tokens are natural stop strings

        def run(on_token=None, on_serve=None):
            t = time.time()
            if BATCHER is not None:
                # The scheduler already runs requests concurrently; a lock here
                # would put back the serialisation it exists to remove.  The
                # KV-free layers are reached inside run_job, which guards them.
                t0 = time.time()
                pre_before, gen_before = E.st["t_pre"], E.st["t_gen"]
                arc_before = E.st.get("arc_s", 0.0)
                r = run_job(E, BATCHER, ids, mx, stops, turn, on_token, on_serve)
            else:
                with LK:
                    w = time.time() - t
                    if w > 1.0:
                        logit(f"waited {w:.1f}s for the engine lock "
                              f"(single context, serial)", "warn")
                    t0 = time.time()
                    pre_before, gen_before = E.st["t_pre"], E.st["t_gen"]
                    arc_before = E.st.get("arc_s", 0.0)
                    r = E.gen(ids, max_new=mx, stop=stops, turn=turn,
                              on_token=on_token, on_serve=on_serve)
            if os.environ.get("CC_DUMP"):
                with open(os.environ["CC_DUMP"], "a", encoding="utf-8") as f:
                    f.write(json.dumps({"prompt": list(ids), "gen": list(r[0]),
                                        "hit": r[2]["hit"]}) + "\n")
            info = r[2]
            # Report the split, not just the total.  A request that reused 21k
            # tokens and generated 578 can take LONGER than one that prefilled
            # 25k and generated 76 -- measured: 12.3 s against 11.8 s, with the
            # reuse actually saving 8.2 s.  Without the split that reads as "the
            # cache made it slower", which is how it got read.
            # The batched path reports these per request.  A batch serves several
            # requests in one llama_decode, so the engine-level counters cannot
            # separate them and the deltas below would credit this request with
            # its neighbours' prefill time; the serial path has no per-job figure
            # and falls back to the deltas, which are exact there.
            pf = info.get("pf")
            gn = info.get("gn")
            if pf is None:
                pf = E.st["t_pre"] - pre_before
            if gn is None:
                gn = E.st["t_gen"] - gen_before
            arcd = E.st.get("arc_s", 0.0) - arc_before
            sec = time.time() - t0
            # Whatever the two counters did not claim.  A batched request is only
            # advanced on the steps it appears in, and _admit can put it straight
            # back on the queue to wait for the worker holding its history -- so
            # without this bucket prefill+decode do not add up to the wall clock
            # and the prefill rate below reads far better than the request felt.
            wait = max(0.0, sec - pf - gn - arcd)
            # Four different speeds, because they answer four different
            # questions and only the first is comparable to a solo prefill:
            #   pre/s  tokens actually forwarded, per second spent forwarding
            #   ctx/s  the whole prompt, per second spent forwarding -- the cache's
            #          contribution included, so a restored prefix shows up here
            #   gen/s  the model's own decode rate, over decode time alone
            #   out/s  what the caller waited for: output over the whole request
            pre_n = info.get("pre") or 0
            out_n = len(r[0])
            rates = []
            if pf > 0:
                if pre_n:
                    rates.append(f"{pre_n / pf:.0f}pre/s")
                if ids:
                    rates.append(f"{len(ids) / pf:.0f}ctx/s")
            if gn > 0 and out_n:
                rates.append(f"{out_n / gn:.0f}gen/s")
            if sec > 0 and out_n:
                rates.append(f"{out_n / sec:.0f}out/s")
            hit_c = "red" if info["hit"] == "batch_cold" else "green"
            # Which of the two ways thinking got turned on -- the client asking
            # for it, or CC_THINK forcing it.  Worth a marker because the two are
            # not equivalent in effect: a server that volunteers a thinking block
            # to a client that never asked has no way to know whether the client
            # has anywhere to put it.
            think_mark = (" req" if req.get("thinking")
                          else " env" if think_on else "")
            msg = (f"{len(ids)}+{out_n} {C(info['hit'], hit_c)} "
                   f"pre={info.get('pre')} reuse={info.get('reuse')} "
                   f"p_raw={info.get('p_raw','-')} cur={info.get('cur','-')} "
                   f"{sec:.1f}s (prefill {pf:.1f}s + decode {gn:.1f}s")
            if wait > 0.05:
                msg += f" + {C('wait', 'yellow')} {wait:.1f}s"
            msg += ")"
            if rates:
                msg += " " + " ".join(rates)
            if arcd > 0.001:
                msg += f" arc_restore={arcd:.2f}s"
            if turn is not None:
                msg += f" turn={turn[0]}:{turn[1].hex()[:8]}"
            if info["hit"] == "qreuse":
                msg += (f" qlevel={info.get('qpreuse')} qwhy={info.get('qwhy')} "
                        f"replayed={info.get('replayed')} "
                        f"edit={info.get('edit_applied')}ok/"
                        f"{info.get('edit_rejected')}rej")
            if info.get("seq") is not None:
                msg += f" seq={info['seq']}"
            # The busiest line in the log; its own tag so it can be picked out.
            log("req " + msg, "info", "req")
            record({"prompt_tokens": len(ids), "gen_tokens": len(r[0]),
                    "hit": info["hit"], "pre": info.get("pre"),
                    "reuse": info.get("reuse"), "p_raw": info.get("p_raw"),
                    "cur": info.get("cur"), "seconds": round(time.time()-t0, 3),
                    "turn_kind": None if turn is None else turn[0],
                    "turn_digest": None if turn is None else turn[1].hex(),
                    "max_tokens": mx, "stream": stream,
                    "qpreuse": info.get("qpreuse"), "qwhy": info.get("qwhy"),
                    "replayed": info.get("replayed"), "edited": info.get("edited"),
                    "edit_applied": info.get("edit_applied"),
                    "edit_rejected": info.get("edit_rejected"),
                    # Deltas, not the engine's running totals: a consumer
                    # reading this file otherwise sees a monotonically growing
                    # "seconds" that is not this request's time.
                    "prefill_seconds": round(pf, 3),
                    "generation_seconds": round(gn, 3)})
            return r

        def parts(text):
            think, body = split_think(text, think_on) if think_on else ("", drop_think(text))
            pre, calls = calls_of(body)
            c = []
            if think.strip():
                c.append({"type": "thinking", "thinking": think.strip(),
                          "signature": THINK_SIG})
            if pre.strip():
                c.append({"type": "text", "text": pre})
            for x in calls:
                c.append({"type": "tool_use", "id": "toolu_" + uuid.uuid4().hex[:20],
                          "name": x["name"], "input": x["arguments"]})
            return (c or [{"type": "text", "text": text}]), ("tool_use" if calls else "end_turn")

        if not stream:
            toks, text, info = run()
            c, why = parts(text)
            return self._send(200, {"id": mid, "type": "message", "role": "assistant",
                                    "model": mdl, "content": c, "stop_reason": why,
                                    "stop_sequence": None,
                                    "usage": usage(len(ids), len(toks),
                                                   info.get("reuse") or 0)})

        # ---- streaming ----
        if not self._head(200, "text/event-stream",
                          [("Cache-Control", "no-cache"),
                           ("Connection", "keep-alive")]):
            return          # already gone: nothing to stream to, and no reply to make
        # message_start is NOT sent here.  Its usage is what Claude Code writes
        # into the session transcript, and the cache fields in it can only be
        # right if the serving layer is already known -- which it is not yet:
        # the probe and the scheduler both decide later, and both decide before
        # a single token is produced.  So it goes out at the first of those
        # moments, or at the latest before any content frame.
        served = {"reuse": 0, "sent": False}
        emit0 = threading.Lock()

        def ensure_start():
            """Write message_start and the opening block once.  Caller holds emit0."""
            if served["sent"]:
                return
            served["sent"] = True
            sse(self, "message_start", {"type": "message_start", "message": {
                "id": mid, "type": "message", "role": "assistant", "model": mdl,
                "content": [], "stop_reason": None, "stop_sequence": None,
                "usage": usage(len(ids), 0, served["reuse"])}})
            # content_block_start travels with it: it used to be emitted up front,
            # which forced message_start out before the serving layer was known
            # and put a zero in the cache fields the client records.
            #
            # In thinking mode the first block is the reasoning, so it is opened
            # as one -- a text block here would have to be closed and reopened
            # before any answer could be sent.
            cb = ({"type": "thinking", "thinking": ""} if think_on
                  else {"type": "text", "text": ""})
            sse(self, "content_block_start", {"type": "content_block_start",
                "index": 0, "content_block": cb})

        def on_serve(reuse, hit):
            served["reuse"] = reuse or 0
            with emit0:
                ensure_start()

        def emit(ev, data):
            # The generation thread and this one both write to the socket -- the
            # generation thread sends text deltas while this one sends pings --
            # and interleaving two SSE frames corrupts both.
            with emit0:
                ensure_start()        # never let content precede message_start
                return sse(self, ev, data)

        st = Streamer(stops, think=think_on, opened=think_on) if STREAM else None
        # Which content block the deltas belong to.  A thinking block has to be
        # opened, filled and closed before the text block opens, so the two
        # cannot share index 0.
        cur_block = [0]
        block_kind = ["thinking" if think_on else "text"]

        def close_block():
            """Close the open block, signature first when it is a thinking one.

            The signature is not optional in the protocol: it is a
            signature_delta immediately before the block's stop, and a client
            that validates the shape drops a block that arrives without it.
            """
            if block_kind[0] == "thinking":
                emit("content_block_delta", {"type": "content_block_delta",
                     "index": cur_block[0],
                     "delta": {"type": "signature_delta",
                               "signature": THINK_SIG}})
            emit("content_block_stop", {"type": "content_block_stop",
                                        "index": cur_block[0]})

        def open_block(kind):
            """Move to the block for ``kind``, closing the previous one."""
            want = 0 if kind == "thinking" else (1 if think_on else 0)
            if want == cur_block[0] and block_kind[0] == kind:
                return
            close_block()
            cb = ({"type": "thinking", "thinking": ""} if kind == "thinking"
                  else {"type": "text", "text": ""})
            emit("content_block_start", {"type": "content_block_start",
                                         "index": want, "content_block": cb})
            cur_block[0], block_kind[0] = want, kind

        def on_tok(chunk):
            """What is safe to send now, computed from the raw chunks.

            The safety rules live in Streamer: nothing from a tool call, nothing
            from inside a think block unless thinking was asked for, nothing from
            a stop string, and nothing that is still a half-formed marker.  What
            comes out has to add up to exactly what the buffered path would have
            sent.
            """
            if st is None:
                return
            for kind, text in st.feed(chunk):
                open_block(kind)
                if kind == "thinking":
                    emit("content_block_delta", {"type": "content_block_delta",
                         "index": cur_block[0],
                         "delta": {"type": "thinking_delta", "thinking": text}})
                else:
                    emit("content_block_delta", {"type": "content_block_delta",
                         "index": cur_block[0],
                         "delta": {"type": "text_delta", "text": text}})

        box, done = [None, None], threading.Event()

        def work():
            # try/finally, not a bare pair: without it a raise inside run() left
            # the flag unset forever, so the handler below pinged every 6 s and
            # never reached message_stop -- and those pings keep the client's
            # idle watchdog alive, so the client waited indefinitely instead of
            # erroring.  The exception is carried out and reported below.
            try:
                box[0] = run(on_tok, on_serve)
            except BaseException as ex:       # noqa: BLE001 - reported below
                box[1] = ex
            finally:
                done.set()

        threading.Thread(target=work, daemon=True).start()
        # Event.wait returns the moment the flag is set, so a reply goes out as
        # soon as it exists.  Polling with a bare time.sleep(6.0) instead -- the
        # earlier shape -- slept the full timeout BEFORE looking, which pushed
        # every reply to the next 6 s boundary: a cache hit answered in 1 ms
        # still reached the client 6 s later.
        while not done.wait(6.0):
            emit("ping", {"type": "ping"})    # keep an idle watchdog from cutting the stream
        if box[1] is not None:
            # The response headers are already sent, so the only honest report is
            # an SSE error event, then close.
            emit("error", {"type": "error",
                           "error": {"type": "api_error", "message": str(box[1])}})
            self.close_connection = True
            return
        if box[0] is None:
            # Unreachable while the loop above waits on done: work() sets
            # box[0] or box[1] in every path.  Asserted so that anything which
            # leaves that loop early fails here with a reason, instead of dying
            # on the unpack with "cannot unpack non-sequence NoneType".
            raise RuntimeError("generation finished without a result")
        toks, text, info = box[0]
        # Everything below writes frames directly, so make sure message_start has
        # gone out first.  It normally has by now (on_serve fired at admission,
        # or the first delta went through emit), but a reply that produced no
        # streamed text at all would otherwise reach message_delta without it.
        with emit0:
            ensure_start()

        # Everything is sent after generation completes, not while generating --
        # tool blocks cannot be streamed character by character or CC sees half a
        # text block first.
        think, body = split_think(text, think_on) if think_on else ("", drop_think(text))
        pre, calls = calls_of(body)

        def send_text(t):
            if not t:
                return
            open_block("text")
            emit("content_block_delta", {"type": "content_block_delta",
                 "index": cur_block[0],
                 "delta": {"type": "text_delta", "text": t}})

        if st is not None:
            # Whatever the safety rules held back, now that the real text is
            # known.  After this the client holds exactly `pre`.
            send_text(st.finish(pre))
            if st.mismatch:
                logit("what was streamed is not a prefix of the buffered text; "
                      "no correction sent, see stream.py", "warn")
        else:
            # No streamer at all (CC_STREAM=0), so nothing has gone out yet: the
            # reasoning and the answer both have to be sent from here.
            if think.strip():
                open_block("thinking")
                emit("content_block_delta", {"type": "content_block_delta",
                     "index": cur_block[0],
                     "delta": {"type": "thinking_delta", "thinking": think.strip()}})
            send_text(pre)
        close_block()
        base = cur_block[0] + 1
        for i, c in enumerate(calls, start=base):
            sse(self, "content_block_start", {"type": "content_block_start", "index": i,
                "content_block": {"type": "tool_use",
                                  "id": "toolu_" + uuid.uuid4().hex[:20],
                                  "name": c["name"], "input": {}}})
            sse(self, "content_block_delta", {"type": "content_block_delta", "index": i,
                "delta": {"type": "input_json_delta",
                          "partial_json": json.dumps(c["arguments"], ensure_ascii=False)}})
            sse(self, "content_block_stop", {"type": "content_block_stop", "index": i})
        sse(self, "message_delta", {"type": "message_delta",
            "delta": {"stop_reason": "tool_use" if calls else "end_turn",
                      "stop_sequence": None},
            # Repeats the whole usage rather than just output_tokens.  Claude
            # Code is known to record the fields from message_start; this one
            # carries the same numbers so a reader that prefers the last usage
            # in the stream sees them too.
            "usage": usage(len(ids), len(toks), info.get("reuse") or 0)})
        sse(self, "message_stop", {"type": "message_stop"})
        # An SSE response has neither Content-Length nor chunked encoding, so
        # under HTTP/1.1 the client can only tell the response ended by the
        # connection CLOSING.  message_stop is only the SSE layer.  Without this,
        # keep-alive reuses the connection and the next request falls into a
        # black hole.
        self.close_connection = True


class Srv(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def handle_error(self, req, addr):
        """CC reconnecting or resetting after a timeout is normal; do not pollute
        the log with a traceback for it."""
        if isinstance(sys.exc_info()[1], (ConnectionResetError, ConnectionAbortedError,
                                          BrokenPipeError, TimeoutError, OSError)):
            return
        super().handle_error(req, addr)

    def process_request_thread(self, req, addr):
        try:
            super().process_request_thread(req, addr)
        except (ConnectionResetError, ConnectionAbortedError, BrokenPipeError,
                TimeoutError, OSError):
            pass


def main():
    global E
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8788)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--n-ctx", type=int, default=131072)
    a = ap.parse_args()
    global BATCHER
    workers = 1
    if os.environ.get("CC_BATCH") == "1":
        workers = max(2, int(os.environ.get("CC_BATCH_N", "4")))
    # The whole sequence budget -- workers, DDC's verification scratch, archive
    # slots -- comes from eng.plan_sequences, which owns the layout and is the
    # same function Eng reads its indices off.  Sized in one place on purpose:
    # when srv.py sized the archive and Eng sized DDC's doubling separately, the
    # two agreed only by accident, and DDC's scratch landed on a sequence the
    # archive had already claimed.
    nseq, n_ctx, ddc_seq = plan_sequences(a.n_ctx, workers)
    if nseq > 1:
        # n_ctx is multiplied so every sequence keeps the full window: the cells
        # are n_ctx in total and llama.cpp divides them across the sequences,
        # which is what makes this cost memory rather than nothing.  Every term
        # is read off the plan rather than assumed -- this line is how the
        # layout gets checked at startup, so a hardcoded count here would be a
        # wrong answer to the question it exists to answer.
        scratch_n = ddc_scratch_count(workers)
        logit(f"nseq {nseq} = {workers} worker(s) + "
              f"{f'{scratch_n} DDC scratch + ' if scratch_n else ''}"
              f"{arc_slot_count()} archive slot(s), "
              f"n_ctx {a.n_ctx} -> {n_ctx} (KV reservation x{nseq})")
    log_setup(LOGDIR)
    log_setup(LOGDIR)
    logit(f"loading engine n_ctx={n_ctx} nseq={nseq}")
    E = Eng(n_ctx=n_ctx, nseq=nseq, workers=workers, log=logit)
    if workers > 1:
        BATCHER = Batcher(E, log=logit)
        logit(f"scheduler up: {len(E.work_seqs)} worker sequences "
              f"{E.work_seqs}, requests run concurrently")
    try:
        os.makedirs(LOGDIR, exist_ok=True)
    except OSError as ex:
        # logit()/record() swallow the same failure, so aborting here after the
        # 5.5 GB model is loaded would contradict the module's own rule.
        logit(f"cannot create log dir {LOGDIR}: {ex} (continuing without it)")
    s = Srv((a.host, a.port), Api)
    logit(f"listening on http://{a.host}:{a.port}")
    logit(f"point Claude Code at: ANTHROPIC_BASE_URL=http://{a.host}:{a.port}")
    logit(f"logs -> {LOGDIR}")
    logit("single context, serial -- concurrent requests queue, that is the inherent bottleneck")
    try:
        s.serve_forever()
    except KeyboardInterrupt:
        logit("exit")
